name: ci_meson

on:
  push:
    paths:
      - "**/meson.build"
      - ".github/workflows/ci_meson.yml"


jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
        cpp: [true, false]

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-14

    name: ${{ matrix.os }} cpp=${{ matrix.cpp }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup -Dcpp=${{ matrix.cpp }} build

    - run: meson compile -C build

    - run: meson test -C build -v
